require("dotenv").config();
const express=require("express"),helmet=require("helmet"),morgan=require("morgan"),crypto=require("crypto"),Razorpay=require("razorpay");
const {db,user,addLedger,order}=require("./db");
const app=express();
const { handleUpdate, setupWebhook } = require("./telegram");app.use(helmet({contentSecurityPolicy:false}));app.use(morgan("tiny"));app.use(express.json({limit:"1mb"}));
app.use(express.static(require("path").join(__dirname,"..","public")));
const PORT=Number(process.env.PORT||3000),QC="https://api.quickcommerceapi.com";
function U(req){const tid=req.headers["x-telegram-id"]||req.body?.telegram_id;return tid?user(tid,req.body?.name||"Web User",req.body?.username||""):null}
async function qc(path,params){if(!process.env.QUICKCOMMERCE_API_KEY)throw Error("QUICKCOMMERCE_API_KEY is not configured");const u=new URL(QC+path);for(const[k,v]of Object.entries(params))if(v!==undefined&&v!=="")u.searchParams.set(k,v);const r=await fetch(u,{headers:{"X-API-Key":process.env.QUICKCOMMERCE_API_KEY}}),d=await r.json();if(!r.ok||d.status==="error")throw Error(d.message||"QuickCommerce request failed");return d}
app.get("/api/health",(q,s)=>s.json({ok:true,brand:"AMZ BB"}));
app.get("/api/me",(req,res)=>{const u=U(req);res.json({user:u?{id:u.id,name:u.name,username:u.username,balance:u.balance}:null})});
app.get("/api/search",async(req,res)=>{try{const{q,lat,lon,pincode}=req.query;if(!q||!lat||!lon)return res.status(400).json({error:"q, lat and lon are required"});res.json(await qc("/v1/search",{q,lat,lon,pincode,platform:"BigBasket"}))}catch(e){res.status(502).json({error:e.message})}});
app.get("/api/item",async(req,res)=>{try{const{item_id,lat,lon,pincode}=req.query;if(!item_id||!lat||!lon)return res.status(400).json({error:"item_id, lat and lon are required"});res.json(await qc("/v1/item",{item_id,lat,lon,pincode,platform:"BigBasket"}))}catch(e){res.status(502).json({error:e.message})}});
app.get("/api/eta",async(req,res)=>{try{const{lat,lon,pincode}=req.query;if(!lat||!lon)return res.status(400).json({error:"lat and lon are required"});res.json(await qc("/v1/eta",{lat,lon,pincode,platform:"BigBasket"}))}catch(e){res.status(502).json({error:e.message})}});
app.post("/api/coupon",(req,res)=>{const c=db.prepare("SELECT * FROM coupons WHERE code=? AND active=1").get(String(req.body.code||"").toUpperCase()),sub=Number(req.body.subtotal||0);if(!c)return res.status(404).json({error:"Invalid coupon"});if(sub<c.min_amount)return res.status(400).json({error:"Minimum order ₹"+c.min_amount});const d=c.type==="percent"?sub*c.value/100:c.value;res.json({code:c.code,discount:Math.min(d,sub)})});
app.get("/api/orders",(req,res)=>{const u=U(req);if(!u)return res.json({orders:[]});const rows=db.prepare("SELECT * FROM orders WHERE user_id=? ORDER BY id DESC LIMIT 50").all(u.id);res.json({orders:rows.map(x=>({...x,items:JSON.parse(x.items_json)}))})});
app.post("/api/orders",(req,res)=>{try{const u=U(req);if(!u)return res.status(400).json({error:"telegram_id required"});const items=req.body.items||[],total=Number(req.body.total||0);if(!items.length||total<=0)return res.status(400).json({error:"Cart is empty"});const id=order(u.id,total,items,req.body.note||"");res.json({ok:true,order_id:id,status:"PENDING",message:"Order queued. Complete purchase on BigBasket using its deeplink."})}catch(e){res.status(400).json({error:e.message==="INSUFFICIENT_BALANCE"?"Insufficient wallet balance":e.message})}});
app.post("/api/bulk",(req,res)=>{const u=U(req);if(!u)return res.status(400).json({error:"telegram_id required"});const p=String(req.body.payload||"").trim();if(!p)return res.status(400).json({error:"Bulk payload required"});const r=db.prepare("INSERT INTO bulk_orders(user_id,payload) VALUES(?,?)").run(u.id,p);res.json({ok:true,bulk_id:r.lastInsertRowid,status:"QUEUED"})});
app.post("/api/razorpay/order",async(req,res)=>{try{const u=U(req);if(!u)return res.status(400).json({error:"telegram_id required"});if(!process.env.RAZORPAY_KEY_ID||!process.env.RAZORPAY_KEY_SECRET)return res.status(503).json({error:"Razorpay keys are not configured"});const amount=Math.round(Number(req.body.amount||0)*100);if(amount<100)return res.status(400).json({error:"Minimum top-up is ₹1"});const r=new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET}),o=await r.orders.create({amount,currency:"INR",receipt:"amzbb_"+Date.now(),notes:{user_id:String(u.id)}});db.prepare("INSERT INTO payments(user_id,razorpay_order_id,amount) VALUES(?,?,?)").run(u.id,o.id,amount/100);res.json({key_id:process.env.RAZORPAY_KEY_ID,order_id:o.id,amount:o.amount,currency:o.currency})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/razorpay/verify",(req,res)=>{try{const u=U(req),{razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body;if(!u||!process.env.RAZORPAY_KEY_SECRET)return res.status(400).json({error:"Payment configuration missing"});const sig=crypto.createHmac("sha256",process.env.RAZORPAY_KEY_SECRET).update(razorpay_order_id+"|"+razorpay_payment_id).digest("hex");if(sig!==razorpay_signature)return res.status(400).json({error:"Invalid payment signature"});const p=db.prepare("SELECT * FROM payments WHERE razorpay_order_id=?").get(razorpay_order_id);if(!p||p.user_id!==u.id)return res.status(400).json({error:"Payment not found"});if(p.status!=="PAID"){db.prepare("UPDATE payments SET razorpay_payment_id=?,status='PAID' WHERE id=?").run(razorpay_payment_id,p.id);addLedger(u.id,"TOPUP",p.amount,razorpay_payment_id)}res.json({ok:true,balance:db.prepare("SELECT balance FROM users WHERE id=?").get(u.id).balance})}catch(e){res.status(500).json({error:e.message})}});
function admin(req,res,next){if(req.headers["x-admin-password"]!==process.env.ADMIN_PASSWORD)return res.status(401).json({error:"Unauthorized"});next()}
app.get("/api/admin/summary",admin,(req,res)=>{res.json({users:db.prepare("SELECT COUNT(*) c FROM users").get().c,orders:db.prepare("SELECT COUNT(*) c FROM orders").get().c,revenue:db.prepare("SELECT COALESCE(SUM(total),0) s FROM orders").get().s,queued:db.prepare("SELECT COUNT(*) c FROM bulk_orders WHERE status='QUEUED'").get().c,recent:db.prepare("SELECT o.id,o.status,o.total,o.created_at,u.name FROM orders o LEFT JOIN users u ON u.id=o.user_id ORDER BY o.id DESC LIMIT 25").all()})});
app.get("/api/admin/users",admin,(req,res)=>res.json({users:db.prepare("SELECT id,telegram_id,name,username,balance,created_at FROM users ORDER BY id DESC LIMIT 200").all()}));
app.get("/api/admin/bulk",admin,(req,res)=>res.json({bulk:db.prepare("SELECT b.id,b.status,b.created_at,u.name FROM bulk_orders b LEFT JOIN users u ON u.id=b.user_id ORDER BY b.id DESC LIMIT 100").all()}));
app.post("/telegram/webhook", async (req,res)=>{ res.sendStatus(200); try { await handleUpdate(req.body); } catch(e) { console.error("Telegram webhook error:", e.message); } });
app.listen(PORT,"0.0.0.0",async()=>{ console.log("AMZ BB server listening on port "+PORT); try { await setupWebhook(); } catch(e) { console.error("Telegram webhook setup failed:",e.message); } });
